### ISSUE TITLE
Implémenter les outils nécessaires

### ISSUE THREAD

**Issue by Eric-Philippe** [Mjolk-Coffee-Concept-Store/Api#1]
# Todo

- [ ] Implémenter une sécurisation des routes (JWT Token)
- [ ] Ajouter un ORM pour joindre Kotlin et PostgreSql
- [ ] Ajouter Swagger sous Kotlin

# Solutions
